### ISSUE TITLE
Paleta de colores

### ISSUE THREAD

**Issue by IbanezAndrea** [juanPedroGalarza/mytinerary-galarza-ibanez#13]
Queria dejar definida una paleta de colores en base a la imagen que usamos de fondo.

Dejo tres paletas hechas de una pagina que cuentan con _almenos_ un tono que utilice anteriormente y que se verian bien con el BG.

-  https://colorhunt.co/palette/ffc8c8ff9999444f5a3e4149
- https://colorhunt.co/palette/dddddd22283130475ef05454
- https://colorhunt.co/palette/faf3e0eabf9fb689731e212d ( Mi favorita de momento)

🐙

**Comment by juanPedroGalarza** [comment]
Me gusta mas el tercero también

**Comment by IbanezAndrea** [comment]
Quedamos en el tercero entonces! 🐙✔✔
